/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Hall.ls
 */
export class HallRTBase extends Laya.Scene {
    public reconnect!: Laya.Dialog;
}

